/**
 * create by Jocs 2016.04.21
 */
import { createConstants } from '../utils'

export default createConstants(

	'LOGIN_USER_REQUEST',
	'LOGIN_USER_SUCCESS',
	'LOGIN_USER_FAILURE',
	'LOGOUT_USER',
	'TOGGLE_LOGIN_PANEL',
	'TOGGLE_LOADING',
	'SIGNUP_SUCCESS',
	'LOGOUT',
	'TOOGLE_CONSOLE_LEFTNAV',
	'OPEN_SNACK_BAR',
	'CLOSE_SNACK_BAR',
	'UNDATE_APP_LIST',
	'ADD_APP_TO_STATE',
	'SELECT_CURRENT_APP',
	'UPDATE_CURRENT_ERROR_LIST',
	'INCREASE_UNREAD_COUNT',
	'TOGGLE_AUTO_REFRESH',
	'SOCKET_CONNECT',
	'SUBSCRIBE',
	'ADD_NEW_TO_ERROR_LIST',
	'UPDATE_DETAIL_ERROR',
	'UPDATE_BROWSERS',
	'UPDATE_STATISTIC',
	'INIT_ERRORS_LOCATION',
	'UPDATE_ERRORS_LOCATION',
	'RESET_DETAIL_ERROR',
	'UPDATE_CITY',
	'CHANGE_THEME',
	'UPDATE_SEARCH_RESULT',
	'PULL_ONE_APP_OUT_OF_LIST'

)
